# Generated by Django 2.2.2 on 2019-06-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_code', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
